//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference2 {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pojo.webservice.service.ybdy.sinobest.cn")]
    public partial class STYDJYException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Exception sTYDJYException1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("STYDJYException", IsNullable=true, Order=0)]
        public Exception STYDJYException1 {
            get {
                return this.sTYDJYException1Field;
            }
            set {
                this.sTYDJYException1Field = value;
                this.RaisePropertyChanged("STYDJYException1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pojo.webservice.service.ybdy.sinobest.cn")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://insurance.jetsun.com/xsd")]
    public partial class DataExchangeServiceReturnType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] outxmlField;
        
        private string syscodeField;
        
        private string sysmsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=0)]
        public byte[] outxml {
            get {
                return this.outxmlField;
            }
            set {
                this.outxmlField = value;
                this.RaisePropertyChanged("outxml");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string syscode {
            get {
                return this.syscodeField;
            }
            set {
                this.syscodeField = value;
                this.RaisePropertyChanged("syscode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string sysmsg {
            get {
                return this.sysmsgField;
            }
            set {
                this.sysmsgField = value;
                this.RaisePropertyChanged("sysmsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pojo.webservice.service.ybdy.sinobest.cn", ConfigurationName="ServiceReference2.STYDJYPortType")]
    public interface STYDJYPortType {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:DataExchangeServiceEnc", ReplyAction="urn:DataExchangeServiceEncResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsFormsApp1.ServiceReference2.STYDJYException), Action="urn:DataExchangeServiceEncSTYDJYException", Name="STYDJYException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp1.ServiceReference2.DataExchangeServiceEncResponse DataExchangeServiceEnc(WindowsFormsApp1.ServiceReference2.DataExchangeServiceEncRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:DataExchangeServiceEnc", ReplyAction="urn:DataExchangeServiceEncResponse")]
        System.IAsyncResult BeginDataExchangeServiceEnc(WindowsFormsApp1.ServiceReference2.DataExchangeServiceEncRequest request, System.AsyncCallback callback, object asyncState);
        
        WindowsFormsApp1.ServiceReference2.DataExchangeServiceEncResponse EndDataExchangeServiceEnc(System.IAsyncResult result);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:test", ReplyAction="urn:testResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsFormsApp1.ServiceReference2.STYDJYException), Action="urn:testSTYDJYException", Name="STYDJYException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp1.ServiceReference2.testResponse test(WindowsFormsApp1.ServiceReference2.testRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:test", ReplyAction="urn:testResponse")]
        System.IAsyncResult Begintest(WindowsFormsApp1.ServiceReference2.testRequest request, System.AsyncCallback callback, object asyncState);
        
        WindowsFormsApp1.ServiceReference2.testResponse Endtest(System.IAsyncResult result);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:STYDJKService", ReplyAction="urn:STYDJKServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsFormsApp1.ServiceReference2.STYDJYException), Action="urn:STYDJKServiceSTYDJYException", Name="STYDJYException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp1.ServiceReference2.STYDJKServiceResponse STYDJKService(WindowsFormsApp1.ServiceReference2.STYDJKServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:STYDJKService", ReplyAction="urn:STYDJKServiceResponse")]
        System.IAsyncResult BeginSTYDJKService(WindowsFormsApp1.ServiceReference2.STYDJKServiceRequest request, System.AsyncCallback callback, object asyncState);
        
        WindowsFormsApp1.ServiceReference2.STYDJKServiceResponse EndSTYDJKService(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DataExchangeServiceEnc", WrapperNamespace="http://pojo.webservice.service.ybdy.sinobest.cn", IsWrapped=true)]
    public partial class DataExchangeServiceEncRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pojo.webservice.service.ybdy.sinobest.cn", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TransNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pojo.webservice.service.ybdy.sinobest.cn", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] inBytes;
        
        public DataExchangeServiceEncRequest() {
        }
        
        public DataExchangeServiceEncRequest(string TransNo, byte[] inBytes) {
            this.TransNo = TransNo;
            this.inBytes = inBytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DataExchangeServiceEncResponse", WrapperNamespace="http://pojo.webservice.service.ybdy.sinobest.cn", IsWrapped=true)]
    public partial class DataExchangeServiceEncResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pojo.webservice.service.ybdy.sinobest.cn", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WindowsFormsApp1.ServiceReference2.DataExchangeServiceReturnType @return;
        
        public DataExchangeServiceEncResponse() {
        }
        
        public DataExchangeServiceEncResponse(WindowsFormsApp1.ServiceReference2.DataExchangeServiceReturnType @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="test", WrapperNamespace="http://pojo.webservice.service.ybdy.sinobest.cn", IsWrapped=true)]
    public partial class testRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pojo.webservice.service.ybdy.sinobest.cn", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TransNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pojo.webservice.service.ybdy.sinobest.cn", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Inxml;
        
        public testRequest() {
        }
        
        public testRequest(string TransNo, string Inxml) {
            this.TransNo = TransNo;
            this.Inxml = Inxml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="testResponse", WrapperNamespace="http://pojo.webservice.service.ybdy.sinobest.cn", IsWrapped=true)]
    public partial class testResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pojo.webservice.service.ybdy.sinobest.cn", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public testResponse() {
        }
        
        public testResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="STYDJKService", WrapperNamespace="http://pojo.webservice.service.ybdy.sinobest.cn", IsWrapped=true)]
    public partial class STYDJKServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pojo.webservice.service.ybdy.sinobest.cn", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TransNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pojo.webservice.service.ybdy.sinobest.cn", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Inxml;
        
        public STYDJKServiceRequest() {
        }
        
        public STYDJKServiceRequest(string TransNo, string Inxml) {
            this.TransNo = TransNo;
            this.Inxml = Inxml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="STYDJKServiceResponse", WrapperNamespace="http://pojo.webservice.service.ybdy.sinobest.cn", IsWrapped=true)]
    public partial class STYDJKServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pojo.webservice.service.ybdy.sinobest.cn", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public STYDJKServiceResponse() {
        }
        
        public STYDJKServiceResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface STYDJYPortTypeChannel : WindowsFormsApp1.ServiceReference2.STYDJYPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataExchangeServiceEncCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DataExchangeServiceEncCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WindowsFormsApp1.ServiceReference2.DataExchangeServiceReturnType Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WindowsFormsApp1.ServiceReference2.DataExchangeServiceReturnType)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class testCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public testCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class STYDJKServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public STYDJKServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class STYDJYPortTypeClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference2.STYDJYPortType>, WindowsFormsApp1.ServiceReference2.STYDJYPortType {
        
        private BeginOperationDelegate onBeginDataExchangeServiceEncDelegate;
        
        private EndOperationDelegate onEndDataExchangeServiceEncDelegate;
        
        private System.Threading.SendOrPostCallback onDataExchangeServiceEncCompletedDelegate;
        
        private BeginOperationDelegate onBegintestDelegate;
        
        private EndOperationDelegate onEndtestDelegate;
        
        private System.Threading.SendOrPostCallback ontestCompletedDelegate;
        
        private BeginOperationDelegate onBeginSTYDJKServiceDelegate;
        
        private EndOperationDelegate onEndSTYDJKServiceDelegate;
        
        private System.Threading.SendOrPostCallback onSTYDJKServiceCompletedDelegate;
        
        public STYDJYPortTypeClient() {
        }
        
        public STYDJYPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public STYDJYPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public STYDJYPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public STYDJYPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<DataExchangeServiceEncCompletedEventArgs> DataExchangeServiceEncCompleted;
        
        public event System.EventHandler<testCompletedEventArgs> testCompleted;
        
        public event System.EventHandler<STYDJKServiceCompletedEventArgs> STYDJKServiceCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference2.DataExchangeServiceEncResponse WindowsFormsApp1.ServiceReference2.STYDJYPortType.DataExchangeServiceEnc(WindowsFormsApp1.ServiceReference2.DataExchangeServiceEncRequest request) {
            return base.Channel.DataExchangeServiceEnc(request);
        }
        
        public WindowsFormsApp1.ServiceReference2.DataExchangeServiceReturnType DataExchangeServiceEnc(string TransNo, byte[] inBytes) {
            WindowsFormsApp1.ServiceReference2.DataExchangeServiceEncRequest inValue = new WindowsFormsApp1.ServiceReference2.DataExchangeServiceEncRequest();
            inValue.TransNo = TransNo;
            inValue.inBytes = inBytes;
            WindowsFormsApp1.ServiceReference2.DataExchangeServiceEncResponse retVal = ((WindowsFormsApp1.ServiceReference2.STYDJYPortType)(this)).DataExchangeServiceEnc(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WindowsFormsApp1.ServiceReference2.STYDJYPortType.BeginDataExchangeServiceEnc(WindowsFormsApp1.ServiceReference2.DataExchangeServiceEncRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDataExchangeServiceEnc(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDataExchangeServiceEnc(string TransNo, byte[] inBytes, System.AsyncCallback callback, object asyncState) {
            WindowsFormsApp1.ServiceReference2.DataExchangeServiceEncRequest inValue = new WindowsFormsApp1.ServiceReference2.DataExchangeServiceEncRequest();
            inValue.TransNo = TransNo;
            inValue.inBytes = inBytes;
            return ((WindowsFormsApp1.ServiceReference2.STYDJYPortType)(this)).BeginDataExchangeServiceEnc(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference2.DataExchangeServiceEncResponse WindowsFormsApp1.ServiceReference2.STYDJYPortType.EndDataExchangeServiceEnc(System.IAsyncResult result) {
            return base.Channel.EndDataExchangeServiceEnc(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WindowsFormsApp1.ServiceReference2.DataExchangeServiceReturnType EndDataExchangeServiceEnc(System.IAsyncResult result) {
            WindowsFormsApp1.ServiceReference2.DataExchangeServiceEncResponse retVal = ((WindowsFormsApp1.ServiceReference2.STYDJYPortType)(this)).EndDataExchangeServiceEnc(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginDataExchangeServiceEnc(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string TransNo = ((string)(inValues[0]));
            byte[] inBytes = ((byte[])(inValues[1]));
            return this.BeginDataExchangeServiceEnc(TransNo, inBytes, callback, asyncState);
        }
        
        private object[] OnEndDataExchangeServiceEnc(System.IAsyncResult result) {
            WindowsFormsApp1.ServiceReference2.DataExchangeServiceReturnType retVal = this.EndDataExchangeServiceEnc(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDataExchangeServiceEncCompleted(object state) {
            if ((this.DataExchangeServiceEncCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DataExchangeServiceEncCompleted(this, new DataExchangeServiceEncCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DataExchangeServiceEncAsync(string TransNo, byte[] inBytes) {
            this.DataExchangeServiceEncAsync(TransNo, inBytes, null);
        }
        
        public void DataExchangeServiceEncAsync(string TransNo, byte[] inBytes, object userState) {
            if ((this.onBeginDataExchangeServiceEncDelegate == null)) {
                this.onBeginDataExchangeServiceEncDelegate = new BeginOperationDelegate(this.OnBeginDataExchangeServiceEnc);
            }
            if ((this.onEndDataExchangeServiceEncDelegate == null)) {
                this.onEndDataExchangeServiceEncDelegate = new EndOperationDelegate(this.OnEndDataExchangeServiceEnc);
            }
            if ((this.onDataExchangeServiceEncCompletedDelegate == null)) {
                this.onDataExchangeServiceEncCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDataExchangeServiceEncCompleted);
            }
            base.InvokeAsync(this.onBeginDataExchangeServiceEncDelegate, new object[] {
                        TransNo,
                        inBytes}, this.onEndDataExchangeServiceEncDelegate, this.onDataExchangeServiceEncCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference2.testResponse WindowsFormsApp1.ServiceReference2.STYDJYPortType.test(WindowsFormsApp1.ServiceReference2.testRequest request) {
            return base.Channel.test(request);
        }
        
        public string test(string TransNo, string Inxml) {
            WindowsFormsApp1.ServiceReference2.testRequest inValue = new WindowsFormsApp1.ServiceReference2.testRequest();
            inValue.TransNo = TransNo;
            inValue.Inxml = Inxml;
            WindowsFormsApp1.ServiceReference2.testResponse retVal = ((WindowsFormsApp1.ServiceReference2.STYDJYPortType)(this)).test(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WindowsFormsApp1.ServiceReference2.STYDJYPortType.Begintest(WindowsFormsApp1.ServiceReference2.testRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Begintest(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Begintest(string TransNo, string Inxml, System.AsyncCallback callback, object asyncState) {
            WindowsFormsApp1.ServiceReference2.testRequest inValue = new WindowsFormsApp1.ServiceReference2.testRequest();
            inValue.TransNo = TransNo;
            inValue.Inxml = Inxml;
            return ((WindowsFormsApp1.ServiceReference2.STYDJYPortType)(this)).Begintest(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference2.testResponse WindowsFormsApp1.ServiceReference2.STYDJYPortType.Endtest(System.IAsyncResult result) {
            return base.Channel.Endtest(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string Endtest(System.IAsyncResult result) {
            WindowsFormsApp1.ServiceReference2.testResponse retVal = ((WindowsFormsApp1.ServiceReference2.STYDJYPortType)(this)).Endtest(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBegintest(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string TransNo = ((string)(inValues[0]));
            string Inxml = ((string)(inValues[1]));
            return this.Begintest(TransNo, Inxml, callback, asyncState);
        }
        
        private object[] OnEndtest(System.IAsyncResult result) {
            string retVal = this.Endtest(result);
            return new object[] {
                    retVal};
        }
        
        private void OntestCompleted(object state) {
            if ((this.testCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.testCompleted(this, new testCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void testAsync(string TransNo, string Inxml) {
            this.testAsync(TransNo, Inxml, null);
        }
        
        public void testAsync(string TransNo, string Inxml, object userState) {
            if ((this.onBegintestDelegate == null)) {
                this.onBegintestDelegate = new BeginOperationDelegate(this.OnBegintest);
            }
            if ((this.onEndtestDelegate == null)) {
                this.onEndtestDelegate = new EndOperationDelegate(this.OnEndtest);
            }
            if ((this.ontestCompletedDelegate == null)) {
                this.ontestCompletedDelegate = new System.Threading.SendOrPostCallback(this.OntestCompleted);
            }
            base.InvokeAsync(this.onBegintestDelegate, new object[] {
                        TransNo,
                        Inxml}, this.onEndtestDelegate, this.ontestCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference2.STYDJKServiceResponse WindowsFormsApp1.ServiceReference2.STYDJYPortType.STYDJKService(WindowsFormsApp1.ServiceReference2.STYDJKServiceRequest request) {
            return base.Channel.STYDJKService(request);
        }
        
        public string STYDJKService(string TransNo, string Inxml) {
            WindowsFormsApp1.ServiceReference2.STYDJKServiceRequest inValue = new WindowsFormsApp1.ServiceReference2.STYDJKServiceRequest();
            inValue.TransNo = TransNo;
            inValue.Inxml = Inxml;
            WindowsFormsApp1.ServiceReference2.STYDJKServiceResponse retVal = ((WindowsFormsApp1.ServiceReference2.STYDJYPortType)(this)).STYDJKService(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WindowsFormsApp1.ServiceReference2.STYDJYPortType.BeginSTYDJKService(WindowsFormsApp1.ServiceReference2.STYDJKServiceRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSTYDJKService(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSTYDJKService(string TransNo, string Inxml, System.AsyncCallback callback, object asyncState) {
            WindowsFormsApp1.ServiceReference2.STYDJKServiceRequest inValue = new WindowsFormsApp1.ServiceReference2.STYDJKServiceRequest();
            inValue.TransNo = TransNo;
            inValue.Inxml = Inxml;
            return ((WindowsFormsApp1.ServiceReference2.STYDJYPortType)(this)).BeginSTYDJKService(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference2.STYDJKServiceResponse WindowsFormsApp1.ServiceReference2.STYDJYPortType.EndSTYDJKService(System.IAsyncResult result) {
            return base.Channel.EndSTYDJKService(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndSTYDJKService(System.IAsyncResult result) {
            WindowsFormsApp1.ServiceReference2.STYDJKServiceResponse retVal = ((WindowsFormsApp1.ServiceReference2.STYDJYPortType)(this)).EndSTYDJKService(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginSTYDJKService(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string TransNo = ((string)(inValues[0]));
            string Inxml = ((string)(inValues[1]));
            return this.BeginSTYDJKService(TransNo, Inxml, callback, asyncState);
        }
        
        private object[] OnEndSTYDJKService(System.IAsyncResult result) {
            string retVal = this.EndSTYDJKService(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSTYDJKServiceCompleted(object state) {
            if ((this.STYDJKServiceCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.STYDJKServiceCompleted(this, new STYDJKServiceCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void STYDJKServiceAsync(string TransNo, string Inxml) {
            this.STYDJKServiceAsync(TransNo, Inxml, null);
        }
        
        public void STYDJKServiceAsync(string TransNo, string Inxml, object userState) {
            if ((this.onBeginSTYDJKServiceDelegate == null)) {
                this.onBeginSTYDJKServiceDelegate = new BeginOperationDelegate(this.OnBeginSTYDJKService);
            }
            if ((this.onEndSTYDJKServiceDelegate == null)) {
                this.onEndSTYDJKServiceDelegate = new EndOperationDelegate(this.OnEndSTYDJKService);
            }
            if ((this.onSTYDJKServiceCompletedDelegate == null)) {
                this.onSTYDJKServiceCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSTYDJKServiceCompleted);
            }
            base.InvokeAsync(this.onBeginSTYDJKServiceDelegate, new object[] {
                        TransNo,
                        Inxml}, this.onEndSTYDJKServiceDelegate, this.onSTYDJKServiceCompletedDelegate, userState);
        }
    }
}
