using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace WindowsFormsApp1.po
{
    public class zybrxx
    {
        //public string sign { get; set; }
        //public string transid { get; set; }
        //public string aab299 { get; set; }
        //public string yab600 { get; set; }
        //public string akb026 { get; set; }
        //public string akb021 { get; set; }
        //public string ykc700 { get; set; }
        //public string aab301 { get; set; }
        //public string yab060 { get; set; }
        //public string aac002 { get; set; }
        //public string aac043 { get; set; }
        //public string aac044 { get; set; }
        public string yzy001 { get; set; }
        public string yzy002 { get; set; }
        public string yzy003 { get; set; }
        public string yzy004 { get; set; }
        public string akc023 { get; set; }
        public string aac003 { get; set; }
        public string aac004 { get; set; }
        public string yzy008 { get; set; }
        public string aac006 { get; set; }
        public string yzy010 { get; set; }
        public string yzy011 { get; set; }
        public string aac161 { get; set; }
        public string yzy013 { get; set; }
        public string aac005 { get; set; }
        public string yzy015 { get; set; }
        public string yzy016 { get; set; }
        public string aac017 { get; set; }
        public string yzy018 { get; set; }
        public string aab004 { get; set; }
        public string yzy020 { get; set; }
        public string yzy021 { get; set; }
        public string yzy022 { get; set; }
        public string aac010 { get; set; }
        public string yzy024 { get; set; }
        public string aae004 { get; set; }
        public string yzy026 { get; set; }
        public string yzy027 { get; set; }
        public string yzy028 { get; set; }
        public string yzy029 { get; set; }
        public string ykc701 { get; set; }
        public string yzy032 { get; set; }
        public string yzy033 { get; set; }
        public string yzy034 { get; set; }
        public string ykc702 { get; set; }
        public string yzy037 { get; set; }
        public string yzy038 { get; set; }
        public string yzy039 { get; set; }
        public string akb063 { get; set; }
        public string akc193 { get; set; }
        public string akc050 { get; set; }
        public string yzy043 { get; set; }
        public string ake022 { get; set; }
        public string yzy045 { get; set; }
        public string yzy046 { get; set; }
        public string yzy047 { get; set; }
        public string yzy048 { get; set; }
        public string yzy049 { get; set; }
        public string yzy050 { get; set; }
        public string yzy051 { get; set; }
        public string yzy052 { get; set; }
        public string yzy053 { get; set; }
        public string yzy054 { get; set; }
        public string yzy055 { get; set; }
        public string yzy056 { get; set; }
        public string yzy057 { get; set; }
        public string yzy058 { get; set; }
        public string yzy059 { get; set; }
        public string yzy060 { get; set; }
        public string yzy061 { get; set; }
        public string yzy062 { get; set; }
        public string yzy063 { get; set; }
        public string yzy064 { get; set; }
        public string yzy065 { get; set; }
        public string yzy066 { get; set; }
        public string yzy067 { get; set; }
        public string yzy068 { get; set; }
        public string yzy069 { get; set; }
        public string akc264 { get; set; }
        public string ake047 { get; set; }
        public string yzy072 { get; set; }
        public string ake050 { get; set; }
        public string ake049 { get; set; }
        public string ake044 { get; set; }
        public string yzy076 { get; set; }
        public string yzy077 { get; set; }
        public string yzy078 { get; set; }
        public string yzy079 { get; set; }
        public string yzy080 { get; set; }
        public string yzy081 { get; set; }
        public string yzy082 { get; set; }
        public string yzy083 { get; set; }
        public string yzy084 { get; set; }
        public string yzy085 { get; set; }
        public string yzy086 { get; set; }
        public string yzy087 { get; set; }
        public string yzy088 { get; set; }
        public string yzy089 { get; set; }
        public string yzy090 { get; set; }
        public string yzy091 { get; set; }
        public string aca111 { get; set; }
        public string yzy093 { get; set; }
        public string yzy094 { get; set; }
        public string yzy095 { get; set; }
        public string yzy096 { get; set; }
        public string yzy097 { get; set; }
        public string yzy098 { get; set; }
        public string yzy099 { get; set; }
        public string yzy100 { get; set; }
        public string yzy101 { get; set; }
        public string yzy102 { get; set; }
        public string yzy103 { get; set; }
        public string yzy104 { get; set; }
        public string yzy105 { get; set; }
        public string yzy106 { get; set; }
        public string yzy107 { get; set; }
        public string yzy108 { get; set; }
        public string yzy109 { get; set; }
        public string yzy110 { get; set; }
        public string yzy111 { get; set; }
        public string yzy112 { get; set; }
        public string yzy113 { get; set; }
        public string yzy114 { get; set; }
        public string yzy115 { get; set; }
        public string yzy116 { get; set; }
        public string yzy117 { get; set; }
        public string yzy118 { get; set; }
        public string yzy119 { get; set; }
        public string yzy120 { get; set; }
        public string yzy121 { get; set; }
        public string yzy122 { get; set; }
        public string yzy123 { get; set; }
        public string yzy124 { get; set; }
        public string yzy125 { get; set; }
        public string yzy126 { get; set; }
        public string yzy127 { get; set; }
        public string yzy128 { get; set; }
        public string yzy129 { get; set; }
        public string yzy130 { get; set; }
        public string yzy131 { get; set; }
        public string yzy132 { get; set; }
        public string yzy133 { get; set; }
        public string yzy134 { get; set; }
        public string yzy135 { get; set; }
        public string yzy136 { get; set; }
        public string yzy137 { get; set; }
        public string yzy138 { get; set; }
        public string yzy139 { get; set; }
        public string yzy140 { get; set; }
        public string yzy141 { get; set; }
        public string yzy142{ get; set; }
        public string yzy143 { get; set; }
        public string yzy144 { get; set; }
        public string yzy145 { get; set; }
        public string yzy146 { get; set; }
        public string yzy147 { get; set; }
        public string yzy148 { get; set; }
        public string yzy149 { get; set; }
        public string yzy150 { get; set; }
        public string yzy151 { get; set; }
        public string yzy152 { get; set; }
        public string yzy153 { get; set; }
        public string yzy154 { get; set; }
        public string yzy155 { get; set; }
        public string yzy156 { get; set; }
        public string yzy157 { get; set; }
        public string yzy158 { get; set; }
        public string yzy159 { get; set; }
        public string yzy160 { get; set; }
        public string yzy161 { get; set; }
        public string yzy162 { get; set; }
        public string yzy163 { get; set; }
        public string yzy164 { get; set; }
        public string yzy165 { get; set; }
        public string yzy166 { get; set; }
        public string yzy167 { get; set; }
        public string yzy168 { get; set; }
        public string yzy169 { get; set; }
        public string yzy170 { get; set; }
        public string yzy171 { get; set; }
        public string yzy172 { get; set; }
        public string yzy173 { get; set; }
        public string yzy174 { get; set; }
       
    }
}
