//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace WindowsFormsApp1.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="STYDJYSoap11Binding", Namespace="http://pojo.webservice.service.ybdy.sinobest.cn")]
    public partial class STYDJY : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DataExchangeServiceEncOperationCompleted;
        
        private System.Threading.SendOrPostCallback testOperationCompleted;
        
        private System.Threading.SendOrPostCallback STYDJKServiceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public STYDJY() {
            this.Url = global::WindowsFormsApp1.Properties.Settings.Default.WindowsFormsApp1_WebReference_STYDJY;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DataExchangeServiceEncCompletedEventHandler DataExchangeServiceEncCompleted;
        
        /// <remarks/>
        public event testCompletedEventHandler testCompleted;
        
        /// <remarks/>
        public event STYDJKServiceCompletedEventHandler STYDJKServiceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:DataExchangeServiceEnc", RequestNamespace="http://pojo.webservice.service.ybdy.sinobest.cn", ResponseNamespace="http://pojo.webservice.service.ybdy.sinobest.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public DataExchangeServiceReturnType DataExchangeServiceEnc([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string TransNo, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)] byte[] inBytes) {
            object[] results = this.Invoke("DataExchangeServiceEnc", new object[] {
                        TransNo,
                        inBytes});
            return ((DataExchangeServiceReturnType)(results[0]));
        }
        
        /// <remarks/>
        public void DataExchangeServiceEncAsync(string TransNo, byte[] inBytes) {
            this.DataExchangeServiceEncAsync(TransNo, inBytes, null);
        }
        
        /// <remarks/>
        public void DataExchangeServiceEncAsync(string TransNo, byte[] inBytes, object userState) {
            if ((this.DataExchangeServiceEncOperationCompleted == null)) {
                this.DataExchangeServiceEncOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDataExchangeServiceEncOperationCompleted);
            }
            this.InvokeAsync("DataExchangeServiceEnc", new object[] {
                        TransNo,
                        inBytes}, this.DataExchangeServiceEncOperationCompleted, userState);
        }
        
        private void OnDataExchangeServiceEncOperationCompleted(object arg) {
            if ((this.DataExchangeServiceEncCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DataExchangeServiceEncCompleted(this, new DataExchangeServiceEncCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:test", RequestNamespace="http://pojo.webservice.service.ybdy.sinobest.cn", ResponseNamespace="http://pojo.webservice.service.ybdy.sinobest.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string test([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string TransNo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Inxml) {
            object[] results = this.Invoke("test", new object[] {
                        TransNo,
                        Inxml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void testAsync(string TransNo, string Inxml) {
            this.testAsync(TransNo, Inxml, null);
        }
        
        /// <remarks/>
        public void testAsync(string TransNo, string Inxml, object userState) {
            if ((this.testOperationCompleted == null)) {
                this.testOperationCompleted = new System.Threading.SendOrPostCallback(this.OntestOperationCompleted);
            }
            this.InvokeAsync("test", new object[] {
                        TransNo,
                        Inxml}, this.testOperationCompleted, userState);
        }
        
        private void OntestOperationCompleted(object arg) {
            if ((this.testCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.testCompleted(this, new testCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:STYDJKService", RequestNamespace="http://pojo.webservice.service.ybdy.sinobest.cn", ResponseNamespace="http://pojo.webservice.service.ybdy.sinobest.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string STYDJKService([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string TransNo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Inxml) {
            object[] results = this.Invoke("STYDJKService", new object[] {
                        TransNo,
                        Inxml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void STYDJKServiceAsync(string TransNo, string Inxml) {
            this.STYDJKServiceAsync(TransNo, Inxml, null);
        }
        
        /// <remarks/>
        public void STYDJKServiceAsync(string TransNo, string Inxml, object userState) {
            if ((this.STYDJKServiceOperationCompleted == null)) {
                this.STYDJKServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSTYDJKServiceOperationCompleted);
            }
            this.InvokeAsync("STYDJKService", new object[] {
                        TransNo,
                        Inxml}, this.STYDJKServiceOperationCompleted, userState);
        }
        
        private void OnSTYDJKServiceOperationCompleted(object arg) {
            if ((this.STYDJKServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.STYDJKServiceCompleted(this, new STYDJKServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://insurance.jetsun.com/xsd")]
    public partial class DataExchangeServiceReturnType {
        
        private byte[] outxmlField;
        
        private string syscodeField;
        
        private string sysmsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] outxml {
            get {
                return this.outxmlField;
            }
            set {
                this.outxmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string syscode {
            get {
                return this.syscodeField;
            }
            set {
                this.syscodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sysmsg {
            get {
                return this.sysmsgField;
            }
            set {
                this.sysmsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void DataExchangeServiceEncCompletedEventHandler(object sender, DataExchangeServiceEncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DataExchangeServiceEncCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DataExchangeServiceEncCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DataExchangeServiceReturnType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DataExchangeServiceReturnType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void testCompletedEventHandler(object sender, testCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class testCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal testCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void STYDJKServiceCompletedEventHandler(object sender, STYDJKServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class STYDJKServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal STYDJKServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591